name: Auto Release on Merge to Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python deps
        run: pip install --upgrade pip

      - name: Update version in README.md
        run: python scripts/update_readme_version.py

      - name: Publish Kotlin 1.9 to GitHub Packages
        run: ./gradlew publishKotlin1.9PublicationToGitHubPackagesRepository --no-daemon
        env:
          GPR_USER: ${{ secrets.GITHUB_ACTOR }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated README.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README with latest version" || echo "No changes to commit"
          git push

      - name: Get version from gradle.properties
        id: get_version
        run: |
          VERSION_NAME=$(grep VERSION_NAME gradle.properties | cut -d'=' -f2)
          echo "version=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Create Git Tag and GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          generate_release_notes: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
